# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: 'macOS-10.15'

resources:
 repositories:
   - repository: microsoft-authentication-library-for-cpp
     type: github
     endpoint: 'GitHub for AzureAD and Azure-Samples (as aadidgit service)'
     name: AzureAD/microsoft-authentication-library-for-cpp
     ref: develop

steps:
# - checkout: self
#   path: CommonCore
- checkout: microsoft-authentication-library-for-cpp
  path: MSAL_CPP # Check out OneAuth to the default working directory so we can use OneAuth templates as-is

# - bash: git -c "user.name=_" -c "user.email=_" subtree pull --prefix=commoncore $AGENT_BUILDDIRECTORY/CommonCore HEAD
#   displayName: Update the CommonCore subtree

- script: |
   cd $(Agent.BuildDirectory)/MSAL_CPP/microsoft-authentication-library-for-cpp/scripts
   python ./build.py
  displayName: 'Run a multi-line script'
