# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: 'macOS-10.15'

resources:
 repositories:
   - repository: microsoft-authentication-library-for-cpp
     type: github
     endpoint: 'GitHub for AzureAD and Azure-Samples (as aadidgit service)'
     name: AzureAD/microsoft-authentication-library-for-cpp
     ref: develop

# steps:
# - checkout: self
#   path: CommonCore
# - checkout: microsoft-authentication-library-for-cpp
#   path: s # Check out OneAuth to the default working directory so we can use OneAuth templates as-is

# - bash: git -c "user.name=_" -c "user.email=_" subtree pull --prefix=deps/msalobjc $AGENT_BUILDDIRECTORY/CommonCore HEAD
#   displayName: Update the CommonCore subtree

# - task: UsePythonVersion@0
#   displayName: Use Python 3.x
  
# - template: azure_pipelines/templates/prebuild.yml@microsoft-authentication-library-for-cpp

# - script: |
#    cd msalcpp
#    python3 ./build.py --platform iOS
#   displayName: 'Run a multi-line script'

jobs:
- job: iOS_OnPrCommit
  displayName: iOS OnPRCommit
  pool:
    vmImage: macOS-10.15
  timeoutInMinutes: 40
  cancelTimeoutInMinutes: 1
  workspace:
    clean: all

  steps:
  - checkout: microsoft-authentication-library-for-cpp
    clean: true
    fetchDepth: 1

  - template: templates/ios-setup.yml@microsoft-authentication-library-for-cpp

  - template: templates/build-and-test.yml@microsoft-authentication-library-for-cpp
    parameters:
      configuration: Debug
      platform: iOS
      arch: x64

  - template: templates/publish-logs.yml@microsoft-authentication-library-for-cpp
    parameters:
      build: true
      testLogArtifactName: 'iOS Test Logs'