# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  branches:
    include:
    - dev

pr:
  autoCancel: true
  branches:
    include:
    - '*'
  drafts: true

pool:
  name: 'Azure Pipelines'

resources:
 repositories:
   - repository: azure-activedirectory-tokenbroker-for-objc
     type: github
     endpoint: 'MSAL ObjC Service Connection'
     name: AzureAD/azure-activedirectory-tokenbroker-for-objc

   - repository: WorkplaceJoin-for-iOS
     type: github
     endpoint: 'MSAL ObjC Service Connection'
     name: AzureAD/WorkplaceJoin-for-iOS

stages:
- stage: Stage_IOS
  displayName: "Validate iOS"
  dependsOn: []
  jobs:
  - job: Validate_Pull_Request_IOS
    displayName: Validate Pull Request (iOS)
    pool:
      vmImage: 'macOS-15'
      timeOutInMinutes: 30
    variables:
      target: "ios_library"
    steps:
    - template: broker_submodule_steps.yml

- stage: Stage_MAC
  displayName: "Validate Mac"
  dependsOn: []
  jobs:
  - job: Validate_Pull_Request_MAC
    displayName: Validate Pull Request (Mac)
    pool:
      vmImage: 'macOS-15'
      timeOutInMinutes: 30
    variables:
      target: "mac_library"
    steps:
    - template: broker_submodule_steps.yml

- stage: Stage_VISION
  displayName: "Validate Vision"
  dependsOn: []
  jobs:
  - job: Validate_Pull_Request_VISION
    displayName: Validate Pull Request (Vision)
    pool:
      vmImage: 'macOS-15'
      timeOutInMinutes: 30
    variables:
      target: "vision_library"
    steps:
    - template: broker_submodule_steps.yml
        
