# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none # Non-PR branches
pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'macOS-11'

resources:
 repositories:
   - repository: microsoft-authentication-library-for-cpp
     type: github
     endpoint: 'GitHub for AzureAD and Azure-Samples (as aadidgit service)'
     name: AzureAD/microsoft-authentication-library-for-cpp
     ref: develop

jobs:
- job: macOS_OnPrCommit
  displayName: MSAL CPP checks per commit for macOS
  timeoutInMinutes: 40
  cancelTimeoutInMinutes: 1
  workspace:
    clean: all

  steps:
  - checkout: self
    path: CommonCore
  - checkout: microsoft-authentication-library-for-cpp
    path: s

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.x'
  - script: |
     cd $(Agent.BuildDirectory)/CommonCore
     commit_number=$(git rev-parse HEAD)
     echo "##vso[task.setvariable variable=commit_number]$(git rev-parse HEAD)"
    displayName: 'Get latest commit number'

  - task: PythonScript@0
    displayName: Update subtree and rename files
    inputs:
     scriptPath: scripts/update_msalobjc_subtree.py
     arguments: '--skip-checkout --msal-common-repo $(Agent.BuildDirectory)/CommonCore --remote-ref $(commit_number)'

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.x'
  - script: |
     /bin/bash -c "sudo xcode-select -s /Applications/Xcode_13.0.app"
    displayName: 'Switch to use Xcode 13'

  - template: azure_pipelines/templates/macos-setup.yml@microsoft-authentication-library-for-cpp

  - task: PythonScript@0
    name: Build
    displayName: 'Build x64 Debug macOS'
    inputs:
      scriptPath: build.py
      arguments: '--clean --arch x64 --configuration Debug --platform macOS --djinni hashfail --test --test-type unit integration'
    env:
      MSAL_LAB_VAULT_ACCESS_CERT_LOCATION: $(Agent.TempDirectory)
      MSAL_CERTIFICATE_PASSWORD: $(MSAL_CERTIFICATE_PASSWORD)
