# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none # Non-PR branches
pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'macOS-14'

variables:
- group: msal-ci-migration-vars

resources:
 repositories:
   - repository: OneAuth
     type: git
     endpoint: 'OfficeADO'
     name: OneAuth/OneAuth
     ref: ios/add-missing-family-refresh-token-type

jobs:
- job: iOS_OnPrCommit
  displayName: OneAuth checks per commit for iOS
  timeoutInMinutes: 40
  cancelTimeoutInMinutes: 1
  workspace:
    clean: all

  steps:
  - checkout: self
    path: CommonCore
  - checkout: OneAuth
    path: s

  - task: UsePythonVersion@0
    displayName: 'Get latest commit number'
  - script: |
     cd $(Agent.BuildDirectory)/CommonCore
     commit_number=$(git rev-parse HEAD)
     echo "##vso[task.setvariable variable=commit_number]$(git rev-parse HEAD)"

  - task: PythonScript@0
    displayName: Update subtree and rename files
    inputs:
     scriptPath: msal/scripts/update_msalobjc_subtree.py
     arguments: '--skip-checkout --msal-common-repo $(Agent.BuildDirectory)/CommonCore --remote-ref $(commit_number)'

  - task: UsePythonVersion@0
    displayName: 'Switch to use Xcode 15.4'
  - script: |
     /bin/bash -c "sudo xcode-select -s /Applications/Xcode_15.4.app"

  - template: msal/azure_pipelines/templates/ios-setup.yml@OneAuth

  - task: PythonScript@0
    name: Build
    displayName: 'Build x64 Debug iOS'
    inputs:
      scriptPath: msal/build.py
      arguments: '--clean --arch x64 --configuration Debug --platform iOS --djinni hashfail --test --test-type unit integration --build-projects tests'
    env:
      MSAL_LAB_VAULT_ACCESS_CERT_LOCATION: $(Agent.TempDirectory)
      MSAL_CERTIFICATE_PASSWORD: $(MSAL_CERTIFICATE_PASSWORD)
