trigger: none # Non-PR branches
pr:
  branches:
    include:
    - '*'
  # TODO: ADO #847765 (Conditional onPrCommit task)
  # paths:
  #   include:
  #   - azure_pipelines/*
  #   - source/xplat/*
  #   - test/unit/xplat/*
  #   - test/integration/xplat/*
  #   - test/end2end/xplat/*
  #   - source/apple/*
  #   - source/mac/*
  #   - test/unit/apple/*
  #   - test/integration/apple/*
  #   - test/end2end/apple/*
  #   - test/unit/mac/*
  #   - test/integration/mac/*
  #   - test/end2end/mac/*

# This pipeline is not tagged as production, but the auto-injected Codesign Validation task takes ~3 minutes to
# configure itself, download all dependencies, and query for the classification tag of the pipeline before it determines
# it has nothing to do. Save this time by skipping that task.
variables:
  runCodesignValidationInjection: false

jobs:
- job: macOS_OnPrCommit
  displayName: x64 Debug
  pool:
    vmImage: macOS-10.15
  timeoutInMinutes: 40
  cancelTimeoutInMinutes: 1
  workspace:
    clean: all

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - template: templates/macos-setup.yml

  - template: templates/build-and-test.yml
    parameters:
      arch: x64
      configuration: Debug
      platform: macOS

  - template: templates/publish-logs.yml
    parameters:
      build: true
      testLogArtifactName: 'macOS Test Logs'

- job: macOS_OnPrCommitHeaderCheck
  displayName: Ensure that all headers are self-contained
  pool:
    vmImage: macOS-10.15
  timeoutInMinutes: 20
  cancelTimeoutInMinutes: 1
  workspace:
    clean: all

  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - template: templates/macos-setup.yml

  - template: templates/build-and-publish.yml
    parameters:
      arch: x64
      configuration: Debug
      platform: macOS
      buildArtifactsName: '' # No artifacts are generated because skipPublish is true
      skipPublish: true
      additionalBuildArgs: --header-check

