name: PR Size Check

on:
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read

jobs:
  check-pr-size:
    uses: AzureAD/azure-activedirectory-tokenbroker-for-objc/.github/workflows/pr-size-check-reusable.yml@swagup/pr_size_check_test
    secrets: inherit